In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('database.csv', index_col=False)

In [10]:
display(df)

,prise,rooms,square,floor,totalFloors,flat/studio,address,coordinate,distanceFromTheCenter,metro,...,hospital,police,shop,beautySalone,mall,museum,pharmacy,sportCenter,postOffice,hotel
0,650000.0,1.0,35.7,2,6,0.0,"Варшавское ш., 125",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8655450.0,5.0,276.0,24,25,1.0,"ул. Лавочкина, 34",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,745000.0,1.0,15.3,16,24,0.0,"Ленинский пр-т, 158",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4999000.0,3.0,88.7,24,27,1.0,"Шелепихинская наб., 42к2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4500000.0,4.0,127.0,4,32,1.0,"пр-т Вернадского, вл78",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4985,1399000.0,2.0,56.0,12,15,1.0,"Скандинавский б-р, 23к2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4986,4350000.0,3.0,105.0,10,32,1.0,"1-й Нагатинский пр., 11к2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4987,1350000.0,2.0,38.4,2,14,1.0,"Озёрная ул., 29к1",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4988,295000.0,1.0,17.7,1,5,0.0,"ул. Орджоникидзе, 6/9",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4989,1987000.0,1.0,42.0,9,16,1.0,"ул. Родченко, 2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
columns_to_check = ['prise', 'rooms', 'square', 'floor', 'totalFloors', 'flat/studio', 'address']

# Фильтрация
index_to_drop = df[df[columns_to_check].isna().any(axis=1)].index

In [17]:
df = df.drop(index_to_drop)

In [18]:
display(df)

,prise,rooms,square,floor,totalFloors,flat/studio,address,coordinate,distanceFromTheCenter,metro,...,hospital,police,shop,beautySalone,mall,museum,pharmacy,sportCenter,postOffice,hotel
0,650000.0,1.0,35.7,2,6,0.0,"Варшавское ш., 125",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8655450.0,5.0,276.0,24,25,1.0,"ул. Лавочкина, 34",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,745000.0,1.0,15.3,16,24,0.0,"Ленинский пр-т, 158",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4999000.0,3.0,88.7,24,27,1.0,"Шелепихинская наб., 42к2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4500000.0,4.0,127.0,4,32,1.0,"пр-т Вернадского, вл78",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4985,1399000.0,2.0,56.0,12,15,1.0,"Скандинавский б-р, 23к2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4986,4350000.0,3.0,105.0,10,32,1.0,"1-й Нагатинский пр., 11к2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4987,1350000.0,2.0,38.4,2,14,1.0,"Озёрная ул., 29к1",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4988,295000.0,1.0,17.7,1,5,0.0,"ул. Орджоникидзе, 6/9",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4989,1987000.0,1.0,42.0,9,16,1.0,"ул. Родченко, 2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.to_csv('database.csv', index=False)