In [5]:
import pandas as pd

In [20]:
df = pd.read_csv('database.csv', index_col=False)

In [21]:
display(df)

,prise,rooms,square,floor,totalFloors,flat/studio,address,coordinate,distanceFromTheCenter,metro,...,hospital,police,shop,beautySalone,mall,museum,pharmacy,sportCenter,postOffice,hotel
0,1430020.0,2.0,49.9,21.0,45.0,1.0,"ш. Перовское, д. 21, корп. 1",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2333100.0,3.0,66.0,2.0,59.0,1.0,"ул. Верейская, д. 29",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,635804.0,1.0,23.7,15.0,18.0,0.0,"пос. Битца, б-р Южный, д. 6",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4639392.0,2.0,72.4,3.0,8.0,1.0,"ул. Часовая, стр. 1.1",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4797995.0,3.0,80.4,16.0,16.0,1.0,"наб. Симоновская, стр. 3",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4964,7500000.0,3.0,89.2,42.0,44.0,1.0,"Ходынская ул., 2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4965,1650000.0,3.0,62.9,9.0,12.0,1.0,"Белореченская ул., 17",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4966,295000.0,1.0,17.7,1.0,5.0,0.0,"ул. Орджоникидзе, 6/9",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4967,335000.0,1.0,15.9,1.0,5.0,0.0,"Волоколамское ш., 80А",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4968,6009400.0,3.0,66.2,4.0,7.0,1.0,"Пречистенская наб., 17-19",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
columns_to_check = ['prise', 'rooms', 'square', 'floor', 'totalFloors', 'flat/studio', 'address', 'coordinate']

# Фильтрация
index_to_drop = df[df[columns_to_check].isna().any(axis=1)].index

KeyError: "['prise'] not in index"

In [23]:
df = df.drop(index_to_drop)

In [27]:
display(df)

,price,rooms,square,floor,totalFloors,flat/studio,address,coordinate,distanceFromTheCenter,metro,...,hospital,police,shop,beautySalone,mall,museum,pharmacy,sportCenter,postOffice,hotel
0,1430020.0,2.0,49.9,21.0,45.0,1.0,"ш. Перовское, д. 21, корп. 1",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2333100.0,3.0,66.0,2.0,59.0,1.0,"ул. Верейская, д. 29",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,635804.0,1.0,23.7,15.0,18.0,0.0,"пос. Битца, б-р Южный, д. 6",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4639392.0,2.0,72.4,3.0,8.0,1.0,"ул. Часовая, стр. 1.1",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4797995.0,3.0,80.4,16.0,16.0,1.0,"наб. Симоновская, стр. 3",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4964,7500000.0,3.0,89.2,42.0,44.0,1.0,"Ходынская ул., 2",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4965,1650000.0,3.0,62.9,9.0,12.0,1.0,"Белореченская ул., 17",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4966,295000.0,1.0,17.7,1.0,5.0,0.0,"ул. Орджоникидзе, 6/9",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4967,335000.0,1.0,15.9,1.0,5.0,0.0,"Волоколамское ш., 80А",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4968,6009400.0,3.0,66.2,4.0,7.0,1.0,"Пречистенская наб., 17-19",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
df.to_csv('database.csv', index=False)

In [100]:
df = pd.read_csv('database.csv')

In [94]:
err_df = pd.read_csv('database_error.csv')

In [57]:
coordinate = err_df['addres']

In [58]:
df['coordinate'] = coordinate

In [106]:
display(df)

,price,rooms,square,floor,totalFloors,flat/studio,address,coordinate,distanceFromTheCenter,metro,...,hospital,police,shop,beautySalone,mall,museum,pharmacy,sportCenter,postOffice,hotel
0,1430020.0,2.0,49.9,21.0,45.0,1.0,"ш. Перовское, д. 21, корп. 1","37.746552,55.736159",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,635804.0,1.0,23.7,15.0,18.0,0.0,"пос. Битца, б-р Южный, д. 6","37.593902,55.557536",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4639392.0,2.0,72.4,3.0,8.0,1.0,"ул. Часовая, стр. 1.1","37.535296,55.806783",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4797995.0,3.0,80.4,16.0,16.0,1.0,"наб. Симоновская, стр. 3","37.651574,55.715160",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2829076.0,1.0,34.4,29.0,36.0,0.0,"пр-т Ленинградский, вл. 8","37.580939,55.780335",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4880,7500000.0,3.0,89.2,42.0,44.0,1.0,"Ходынская ул., 2","37.564212,55.770806",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4881,1650000.0,3.0,62.9,9.0,12.0,1.0,"Белореченская ул., 17","37.767052,55.672676",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4882,295000.0,1.0,17.7,1.0,5.0,0.0,"ул. Орджоникидзе, 6/9","37.598007,55.710692",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4883,335000.0,1.0,15.9,1.0,5.0,0.0,"Волоколамское ш., 80А","37.461876,55.820369",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4884,6009400.0,3.0,66.2,4.0,7.0,1.0,"Пречистенская наб., 17-19","37.605508,55.739732",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
display(coordinate)

0        37.746552,55.736159
1        37.436292,55.711032
2        37.593902,55.557536
3        37.535296,55.806783
4        37.651574,55.715160
                ...
4880     37.564212,55.770806
4881     37.767052,55.672676
4882     37.598007,55.710692
4883     37.461876,55.820369
4884     37.605508,55.739732
Name: addres, Length: 4885, dtype: object

In [74]:
for i in range(len(coordinate)):
    coordinate_ = str(coordinate[i])[1:]
    if len(coordinate_) == 19:
        df.loc[i, 'coordinate'] = coordinate_
    else:
        df.loc[i, 'coordinate'] =  ' '

In [75]:
len('37.479115,55.878536')

19

In [107]:
df.to_csv('database.csv', index=False)

In [103]:


# Фильтрация
index_to_drop = df[(df['coordinate'].isna()) | (df['coordinate'] == ' ')].index

In [105]:
df = df.drop(index_to_drop)